# generated by datamodel-codegen:
#   filename:  query-plan.schema.json
#   timestamp: 2026-01-05T13:28:52+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Optional, Union

from pydantic import AwareDatetime, BaseModel, Field


class Entity(Enum):
    """
    논리 엔티티명 (물리 테이블명 아님)
    """

    order = 'Order'
    customer = 'Customer'
    product = 'Product'
    inventory = 'Inventory'
    payment_log = 'PaymentLog'


class Operation(Enum):
    """
    쿼리 작업 유형
    """

    list = 'list'
    aggregate = 'aggregate'
    search = 'search'


class Operator(Enum):
    """
    비교 연산자
    """

    eq = 'eq'
    ne = 'ne'
    gt = 'gt'
    gte = 'gte'
    lt = 'lt'
    lte = 'lte'
    in_ = 'in'
    like = 'like'
    between = 'between'


class Filter(BaseModel):
    field: str
    """
    논리 필드명
    """
    operator: Operator
    """
    비교 연산자
    """
    value: Union[str, float, bool, list[Any]]
    """
    비교 값 (타입은 필드에 따라 다름)
    """


class Function(Enum):
    """
    집계 함수
    """

    count_ = 'count'
    sum = 'sum'
    avg = 'avg'
    min = 'min'
    max = 'max'


class Aggregation(BaseModel):
    function: Function
    """
    집계 함수
    """
    field: str
    """
    집계 대상 필드
    """
    alias: Optional[str] = None
    """
    집계 결과 별칭
    """


class Direction(Enum):
    """
    정렬 방향
    """

    asc = 'asc'
    desc = 'desc'


class OrderByItem(BaseModel):
    field: str
    """
    정렬 필드명
    """
    direction: Direction
    """
    정렬 방향
    """


class TimeRange(BaseModel):
    """
    시계열 데이터 조회 시 필수 시간 범위
    """

    start: AwareDatetime
    """
    시작 시간 (ISO 8601)
    """
    end: AwareDatetime
    """
    종료 시간 (ISO 8601)
    """


class QueryPlan(BaseModel):
    """
    AI Orchestrator가 Core API에 전달하는 쿼리 계획
    """

    request_id: str = Field(..., alias='requestId', min_length=1)
    """
    요청 고유 ID
    """
    entity: Entity
    """
    논리 엔티티명 (물리 테이블명 아님)
    """
    operation: Operation
    """
    쿼리 작업 유형
    """
    filters: Optional[list[Filter]] = None
    """
    필터 조건 목록
    """
    aggregations: Optional[list[Aggregation]] = None
    """
    집계 조건 목록
    """
    group_by: Optional[list[str]] = Field(None, alias='groupBy')
    """
    그룹화 필드 목록
    """
    order_by: Optional[list[OrderByItem]] = Field(None, alias='orderBy')
    """
    정렬 조건 목록
    """
    limit: Optional[int] = Field(10, ge=1, le=1000)
    """
    최대 조회 개수
    """
    query_token: Optional[str] = Field(None, alias='queryToken')
    """
    서버사이드 페이징 토큰 (다음 페이지 조회 시 사용)
    """
    time_range: Optional[TimeRange] = Field(None, alias='timeRange')
    """
    시계열 데이터 조회 시 필수 시간 범위
    """
