# generated by datamodel-codegen:
#   filename:  render-spec.schema.json
#   timestamp: 2026-01-05T13:28:54+00:00

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import AwareDatetime, BaseModel, Field


class Type(Enum):
    """
    렌더링 타입
    """

    table = 'table'
    text = 'text'
    chart = 'chart'
    log = 'log'
    composite = 'composite'


class Type1(Enum):
    """
    데이터 타입
    """

    string = 'string'
    number = 'number'
    date = 'date'
    boolean = 'boolean'
    currency = 'currency'
    percentage = 'percentage'


class Align(Enum):
    """
    텍스트 정렬
    """

    left = 'left'
    center_ = 'center'
    right = 'right'


class Column(BaseModel):
    key: str
    """
    데이터 필드 키
    """
    label: str
    """
    컬럼 헤더 레이블
    """
    type: Optional[Type1] = None
    """
    데이터 타입
    """
    format: Optional[str] = Field(
        None, examples=['YYYY-MM-DD', '0,0.00', 'currency:KRW']
    )
    """
    표시 포맷
    """
    align: Optional[Align] = None
    """
    텍스트 정렬
    """
    sortable: Optional[bool] = None
    """
    정렬 가능 여부
    """
    width: Optional[str] = Field(None, examples=['100px', '20%', 'auto'])
    """
    컬럼 너비
    """


class Action1(Enum):
    """
    액션 타입
    """

    export_csv = 'export-csv'
    fullscreen = 'fullscreen'
    refresh = 'refresh'
    custom = 'custom'


class Action(BaseModel):
    label: str
    """
    버튼 레이블
    """
    action: Action1
    """
    액션 타입
    """
    icon: Optional[str] = None
    """
    아이콘 이름
    """


class Type2(Enum):
    """
    페이지네이션 타입
    """

    load_more = 'load-more'
    infinite_scroll = 'infinite-scroll'
    page_numbers = 'page-numbers'


class Pagination(BaseModel):
    """
    페이지네이션 설정
    """

    enabled: Optional[bool] = None
    """
    페이지네이션 사용 여부
    """
    type: Optional[Type2] = None
    """
    페이지네이션 타입
    """
    page_size: Optional[int] = Field(None, alias='pageSize')
    """
    페이지당 행 개수
    """


class Table(BaseModel):
    """
    테이블 렌더링 설정 (type=table일 때)
    """

    columns: Optional[list[Column]] = None
    """
    테이블 컬럼 정의
    """
    data_ref: Optional[str] = Field('data.rows', alias='dataRef')
    """
    데이터 참조 경로 (QueryResult 내 경로)
    """
    actions: Optional[list[Action]] = None
    """
    행 액션 버튼 목록
    """
    pagination: Optional[Pagination] = None
    """
    페이지네이션 설정
    """


class Format(Enum):
    """
    텍스트 포맷
    """

    markdown = 'markdown'
    plain = 'plain'
    html = 'html'


class Type3(Enum):
    info = 'info'
    warning = 'warning'
    error = 'error'
    success = 'success'


class Section(BaseModel):
    type: Optional[Type3] = None
    title: Optional[str] = None
    content: Optional[str] = None


class Text(BaseModel):
    """
    텍스트 렌더링 설정 (type=text일 때)
    """

    content: Optional[str] = None
    """
    텍스트 내용 (Markdown 지원)
    """
    format: Optional[Format] = None
    """
    텍스트 포맷
    """
    sections: Optional[list[Section]] = None
    """
    섹션별 텍스트 (여러 블록으로 나눌 때)
    """


class ChartType(Enum):
    """
    차트 종류
    """

    bar = 'bar'
    line = 'line'
    pie = 'pie'
    area = 'area'
    scatter = 'scatter'
    composed = 'composed'


class Type4(Enum):
    category = 'category'
    number = 'number'
    time = 'time'


class XAxis(BaseModel):
    """
    X축 설정
    """

    data_key: Optional[str] = Field(None, alias='dataKey')
    """
    X축 데이터 필드
    """
    label: Optional[str] = None
    """
    X축 레이블
    """
    type: Optional[Type4] = None


class Type5(Enum):
    number = 'number'


class YAxis(BaseModel):
    """
    Y축 설정
    """

    data_key: Optional[str] = Field(None, alias='dataKey')
    """
    Y축 데이터 필드
    """
    label: Optional[str] = None
    """
    Y축 레이블
    """
    type: Optional[Type5] = None


class Type6(Enum):
    bar = 'bar'
    line = 'line'
    area = 'area'


class Series(BaseModel):
    data_key: Optional[str] = Field(None, alias='dataKey')
    name: Optional[str] = None
    color: Optional[str] = None
    type: Optional[Type6] = None


class Chart(BaseModel):
    """
    차트 렌더링 설정 (type=chart일 때)
    """

    chart_type: Optional[ChartType] = Field(None, alias='chartType')
    """
    차트 종류
    """
    data_ref: Optional[str] = Field('data.rows', alias='dataRef')
    """
    데이터 참조 경로
    """
    x_axis: Optional[XAxis] = Field(None, alias='xAxis')
    """
    X축 설정
    """
    y_axis: Optional[YAxis] = Field(None, alias='yAxis')
    """
    Y축 설정
    """
    series: Optional[list[Series]] = None
    """
    데이터 시리즈 (여러 그래프 표시 시)
    """
    legend: Optional[bool] = None
    """
    범례 표시 여부
    """
    tooltip: Optional[bool] = None
    """
    툴팁 표시 여부
    """


class Level(Enum):
    debug = 'DEBUG'
    info = 'INFO'
    warn = 'WARN'
    error = 'ERROR'
    fatal = 'FATAL'


class Filter(BaseModel):
    """
    로그 필터 설정
    """

    levels: Optional[list[Level]] = None
    """
    표시할 로그 레벨
    """
    searchable: Optional[bool] = None
    """
    검색 기능 활성화
    """


class Log(BaseModel):
    """
    로그 렌더링 설정 (type=log일 때)
    """

    data_ref: Optional[str] = Field('data.rows', alias='dataRef')
    """
    로그 데이터 참조 경로
    """
    timestamp_key: Optional[str] = Field('timestamp', alias='timestampKey')
    """
    타임스탬프 필드 키
    """
    level_key: Optional[str] = Field('level', alias='levelKey')
    """
    로그 레벨 필드 키
    """
    message_key: Optional[str] = Field('message', alias='messageKey')
    """
    로그 메시지 필드 키
    """
    highlight: Optional[list[str]] = None
    """
    하이라이트할 키워드 목록
    """
    filter: Optional[Filter] = None
    """
    로그 필터 설정
    """


class Layout(Enum):
    """
    레이아웃 방식
    """

    vertical = 'vertical'
    horizontal = 'horizontal'
    grid = 'grid'


class Metadata(BaseModel):
    """
    렌더링 메타데이터
    """

    request_id: Optional[str] = Field(None, alias='requestId')
    """
    원본 요청 ID
    """
    generated_at: Optional[AwareDatetime] = Field(None, alias='generatedAt')
    """
    RenderSpec 생성 시각
    """
    version: Optional[str] = None
    """
    RenderSpec 버전
    """


class Composite(BaseModel):
    """
    복합 렌더링 설정 (여러 컴포넌트 조합, type=composite일 때)
    """

    layout: Optional[Layout] = None
    """
    레이아웃 방식
    """
    components: Optional[list[RenderSpec]] = None
    """
    하위 컴포넌트 목록 (재귀적 RenderSpec)
    """


class RenderSpec(BaseModel):
    """
    AI Orchestrator가 UI에 전달하는 렌더링 명세
    """

    type: Type
    """
    렌더링 타입
    """
    title: Optional[str] = None
    """
    렌더 컴포넌트 제목
    """
    description: Optional[str] = None
    """
    렌더 컴포넌트 설명
    """
    table: Optional[Table] = None
    """
    테이블 렌더링 설정 (type=table일 때)
    """
    text: Optional[Text] = None
    """
    텍스트 렌더링 설정 (type=text일 때)
    """
    chart: Optional[Chart] = None
    """
    차트 렌더링 설정 (type=chart일 때)
    """
    log: Optional[Log] = None
    """
    로그 렌더링 설정 (type=log일 때)
    """
    composite: Optional[Composite] = None
    """
    복합 렌더링 설정 (여러 컴포넌트 조합, type=composite일 때)
    """
    metadata: Optional[Metadata] = None
    """
    렌더링 메타데이터
    """


Composite.model_rebuild()
