#!/bin/bash

set -e

# 색상 출력
GREEN='\033[0;32m'
BLUE='\033[0;34m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "${BLUE}================================${NC}"
echo -e "${BLUE}타입 생성 스크립트${NC}"
echo -e "${BLUE}================================${NC}"
echo ""

# 프로젝트 루트 디렉토리
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CONTRACTS_DIR="$PROJECT_ROOT/libs/contracts"

# Python 타입 생성
echo -e "${GREEN}[1/2] Python 타입 생성 중...${NC}"

PYTHON_OUTPUT_DIR="$PROJECT_ROOT/services/ai-orchestrator/app/models"
mkdir -p "$PYTHON_OUTPUT_DIR"

# datamodel-code-generator 설치 확인
if ! python3 -c "import datamodel_code_generator" &> /dev/null; then
    echo -e "${RED}datamodel-codegen이 설치되어 있지 않습니다.${NC}"
    echo "설치 중: pip3 install datamodel-code-generator"
    pip3 install datamodel-code-generator
fi

# 각 스키마에 대해 타입 생성
for schema in "$CONTRACTS_DIR"/*.schema.json; do
    filename=$(basename "$schema" .schema.json)
    echo "  - $filename.py 생성 중..."

    python3 -m datamodel_code_generator \
        --input "$schema" \
        --output "$PYTHON_OUTPUT_DIR/${filename}.py" \
        --input-file-type jsonschema \
        --output-model-type pydantic_v2.BaseModel \
        --use-standard-collections \
        --use-schema-description \
        --use-field-description \
        --field-constraints \
        --snake-case-field
done

# __init__.py 생성
cat > "$PYTHON_OUTPUT_DIR/__init__.py" << 'EOF'
"""
Auto-generated models from JSON Schema
Generated by: scripts/generate-types.sh
"""

from .query_plan import QueryPlan
from .query_result import QueryResult
from .render_spec import RenderSpec

__all__ = ["QueryPlan", "QueryResult", "RenderSpec"]
EOF

echo -e "${GREEN}✓ Python 타입 생성 완료: $PYTHON_OUTPUT_DIR${NC}"
echo ""

# Java 타입 생성
echo -e "${GREEN}[2/2] Java 타입 생성 중...${NC}"

JAVA_OUTPUT_DIR="$PROJECT_ROOT/services/core-api/src/main/java/com/chatops/core/domain/model"
mkdir -p "$JAVA_OUTPUT_DIR"

# jsonschema2pojo 실행 (Gradle 플러그인 사용)
cd "$PROJECT_ROOT/services/core-api"

# Gradle 태스크 실행
echo "  - Gradle jsonschema2pojo 태스크 실행 중..."
./gradlew generateJsonSchema2Pojo --quiet

echo -e "${GREEN}✓ Java 타입 생성 완료: $JAVA_OUTPUT_DIR${NC}"
echo ""

# 요약
echo -e "${BLUE}================================${NC}"
echo -e "${GREEN}✓ 타입 생성 완료!${NC}"
echo -e "${BLUE}================================${NC}"
echo ""
echo "생성된 파일:"
echo "  Python: services/ai-orchestrator/app/models/"
echo "    - query_plan.py"
echo "    - query_result.py"
echo "    - render_spec.py"
echo ""
echo "  Java: services/core-api/src/main/java/com/chatops/core/domain/model/"
echo "    - QueryPlan.java"
echo "    - QueryResult.java"
echo "    - (RenderSpec.java는 Core API에서 불필요)"
echo ""
echo -e "${BLUE}다음 단계: 생성된 타입을 기존 코드에 적용하세요.${NC}"
